### PR TITLE
▶💥 Fix seg fault after failed service connection StartStream

### LINKED ISSUE #69: Seg fault: Null pointer dereference in FtlControlConnection::stopConnection()
Somehow we're in a state where an `FtlControlConnection` has a null `transport` value...

Crash dump `core.janus.705963.1612985766`

```log
Feb 10 19:36:06 do-nyc3-ingest1.kjfk.live.glimesh.tv janus[705963]: [2021-02-10 19:36:06.095] [info] New FTL control connection is pending.
Feb 10 19:36:06 do-nyc3-ingest1.kjfk.live.glimesh.tv janus[705963]: [2021-02-10 19:36:06.156] [info] Channel 689 authenticated successfully.
Feb 10 19:36:06 do-nyc3-ingest1.kjfk.live.glimesh.tv janus[705963]: [2021-02-10 19:36:06.166] [warning] Received unrecognized attribute from client: ProtocolVersion: 0.9
Feb 10 19:36:06 do-nyc3-ingest1.kjfk.live.glimesh.tv janus[705963]: [2021-02-10 19:36:06.233] [error] Could not assign media port for FTL connection.
Feb 10 19:36:06 do-nyc3-ingest1.kjfk.live.glimesh.tv systemd[1]: janus.service: Main process exited, code=killed, status=11/SEGV
Feb 10 19:36:06 do-nyc3-ingest1.kjfk.live.glimesh.tv systemd[1]: janus.service: Failed with result 'signal'.
```

```gdb
#0  0x00007fc368f12b2b in FtlControlConnection::stopConnection() (this=0x7fc344002040)
    at /usr/include/c++/10/bits/unique_ptr.h:421
#1  0x00007fc368f13c90 in FtlControlConnection::processDotCommand() (this=0x7fc344002040)
    at ../src/FtlControlConnection.cpp:428
#2  0x00007fc368f15986 in FtlControlConnection::onTransportBytesReceived(std::vector<std::byte, std::allocator<std::byte> > const&) (this=0x7fc344002040, bytes=...) at ../src/FtlControlConnection.cpp:92
#3  0x00007fc368f07bb1 in std::function<void (std::vector<std::byte, std::allocator<std::byte> > const&)>::operator()(std::vector<std::byte, std::allocator<std::byte> > const&) const
    (__args#0=std::vector of length 262, capacity 262 = {...}, this=0x7fc344000c38)
    at /usr/include/c++/10/bits/std_function.h:617
#4  NetworkSocketConnectionTransport::connectionThreadBody(std::promise<void>&&)
    (this=0x7fc344000b90, connectionThreadEndedPromise=...)
    at ../src/ConnectionTransports/NetworkSocketConnectionTransport.cpp:274
#5  0x00007fc368d34d84 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fc36c1ac609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#7  0x00007fc36c0d3293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

### PR DESCRIPTION
**Pull request by haydenmc**
Fixes #69 

The `FtlControlConnection::onStartMediaPort` callback would sometimes lead to a crash due to `FtlServer` prematurely removing the `FtlControlConnection` from the pending connection store - if an error occurs during stream negotiation inside of `FtlServer::onControlStartMediaPort` (such as the service connection refusing the StartStream request), the `FtlControlConnection` instance would be destructed before it is able to handle the error.

Fixed by waiting to remove the `FtlControlConnection` from the pending connection store until the control connection has successfully been handed off to `FtlStream`.

### CODE REVIEW

File: src/FtlServer.cpp [hunk 1]
```diff
@@ -166,8 +166,11 @@ Result<uint16_t> FtlServer::onControlStartMediaPort(FtlControlConnection& contro
     {
         throw std::runtime_error("Unknown control connection requested a media port assignment");
     }
-    std::unique_ptr<FtlControlConnection> control = std::move(pendingControlConnections[&controlConnection]);
-    pendingControlConnections.erase(&controlConnection);
+
+    // Don't erase the connection from the pending store just yet -
+    // if there's an error assigning it a port, we need to keep it around so it can handle it!
+    std::unique_ptr<FtlControlConnection>& control = 
+        pendingControlConnections.at(&controlConnection);
```
Comment (danstiner) [inline src/FtlServer.cpp:173]: Won't this cause an issue on line 200?

Honestly would expect the compiler to catch the issue, looks like creating the FtlStream consumes the control connection unique_ptr while the ptr is also still in the map. My C++ is rusty but that seems bad, maybe the `std::move(control)` on the lvalue reference bypasses the compiler safety?

Comment (haydenmc) [reply src/FtlServer.cpp:173]: This is a reference to the unique_ptr inside of the map, so no construction is happening afaik. At line 200, std::move causes the move constructor for unique_ptr to be used to transfer ownership of the the unique_ptr to the new FtlStream, so when `control` leaves scope, it's empty.

File: src/FtlServer.cpp [hunk 2]
```diff
@@ -198,6 +201,8 @@ Result<uint16_t> FtlServer::onControlStartMediaPort(FtlControlConnection& contro
         std::bind(&FtlServer::onStreamClosed, this, std::placeholders::_1),
         std::bind(&FtlServer::onStreamRtpPacket, this, std::placeholders::_1, std::placeholders::_2,
             std::placeholders::_3));
+    pendingControlConnections.erase(&controlConnection);
```
[the remark this answers is not in the document]
Comment (haydenmc) [reply src/FtlServer.cpp:204]: Commented below on my logic here :)

File: src/FtlServer.cpp (hunk 1 above)
Comment (danstiner) [reply src/FtlServer.cpp:173]: Ahhhhh yeah that makes sense. An empty unique_ptr basically acts as a nullptr right so this is much more normal than I thought, thanks!

**Review by danstiner — APPROVED** [review]
